project:
  type: website
website:
  title: "Quantitative Approach in Linguistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Materials
        menu:
          - href: descriptive-stats-qualitative.qmd
            text: "Descriptive Statistics for Qualitative Variable with R"